import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

const GROUP_MAP: Record<string, string> = {
  "1167 n kingsley drive llc": "Baljit Gambhir",
  "15295 i-35 llc": "Saritha",
  "1624 bonnie brae llc": "Baljit Gambhir",
  "215 fargo st": "SFT Group",
  "2422 wheeler llc": "Jamil Hasan",
  "2607 grant llc": "Fred & Soodi Sharifi Family P'Ship",
  "2824 isabella llc": "Jamil Hasan",
  "303a properties llc": "Kalcorp",
  "3527 ruth llc": "Jamil Hasan",
  "3607 rosalie llc": "Jamil Hasan",
  "3831 cosby llc": "Jamil Hasan",
  "410 w main llc": "Baljit Gambhir",
  "4529 kingsbury llc": "Jamil Hasan",
  "4530 kingsbury llc": "Jamil Hasan",
  "4802 old spanish trail": "Jamil Hasan",
  "4823 jackson st llc": "Baljit Gambhir",
  "4910 dickens llc": "Jamil Hasan",
  "5020 page properties llc": "Baljit/B S Gambhir Family Ptr",
  "5107 yellowstone llc": "Jamil Hasan",
  "6031 beekman": "Jamil Hasan",
  "6634 stearns llc": "Jamil Hasan",
  "8623 norton llc": "Jamil Hasan",
  "8829 carousel llc": "Jamil Hasan",
  "a & b gp llc": "Anand & Bela Jain Group",
  "a&b jain family partnership ltd": "RPBS/Anand & Bela",
  "a-1 personnel of houston inc": "Khemka",
  "aas real estate ventures llc": "Amanul Syed",
  "ability ai services  llc": "Sanjukta B Mukherji",
  "access parking systems inc": "Moe Elmorabit",
  "acclaimed trading inc": "RPBS/Outside Shareholders",
  "adjeva llc (dba another broken egg caf\u00e9) - vintage": "Paul Sikand",
  "adjewa llc (dba another broken egg caf\u00e9) - pearland": "Paul Sikand",
  "advanced spine & pain specialist": "Dr Andrew Khoury Group",
  "aig real estate holdings llc": "Asad Abbassi",
  "ali ebrahim limited partnership": "Ebrahim Mo & Ali",
  "alishah brewster st llc": "Shah",
  "alishah market llc": "Shah",
  "alishah ventures llc": "Shah",
  "altruvista llc": "Ali Nasser",
  "altruvista rmc llc": "Ali Nasser",
  "altusa office warehouse association inc": "VKC",
  "american book buy.com inc (mi)": "RPBS/Outside Shareholders",
  "american linen llc": "Ebrahim Mo & Ali",
  "amigo topups llc": "Amanul Syed",
  "amvilal group llc": "Shonali",
  "amvira llc": "Shonali",
  "amviram holdings ltd": "Shonali",
  "amviram holdings management llc": "Shonali",
  "ana holding corporation": "Sarah Alabaykan",
  "aps organization inc": "RPBS/Outside Shareholders",
  "asaa estates llc": "Amanul Syed",
  "ashirvaad lp": "Dr Subhash Bannerji",
  "aspire enterprise llc": "RPBS/Anand & Bela",
  "asset holding partnership ltd": "Ron",
  "astm ventures llc": "Shah",
  "avibhore llc": "RPBS/Vibhore Jain",
  "b & s agrawal family gp llc": "VKC",
  "b & s agrawal family lp": "VKC",
  "b & s gambhir family partnership ltd": "Baljit Gambhir",
  "ba & cs llc": "Steve Foster",
  "bamex management inc (de)": "Amanul Syed",
  "barcelona2015 llc": "Nirav Patel",
  "barclay operations llc": "Malik",
  "barton springs lamar llc": "Saritha",
  "bdesh estates llc": "Amanul Syed",
  "bertha drive inc": "Humaira Group",
  "bk & malik inc": "Malik",
  "boleh industries llc": "Micah Simmons",
  "boleh real estate llc": "Micah Simmons",
  "brij & sunita agrawal foundation": "VKC",
  "brookline partners llc": "John Page",
  "c&h transportation & bus rentals llc": "Ron",
  "cabomex estates llc (de)": "Amanul Syed",
  "cakebites llc": "VKC Group",
  "canaan shalom holdings inc": "Leslie Bernal",
  "canaan shalom logistics llc": "Leslie Bernal",
  "canaan shalom transport llc": "Leslie Bernal",
  "chawla enterprises llc  (dba rc property management)": "Vipandeep",
  "clark, duncan & morris inc": "Peter M",
  "coh greenfield apartments llc": "John Page",
  "collegiate outfitters llc": "Kalcorp",
  "comense investments llc": "Venkat Gujja",
  "cyber zone us llc": "Sam Samara Group",
  "davis days": "Josh Davis",
  "devyani management llc": "Shonali",
  "dhacam holdings lp (de)": "Amanul Syed",
  "diastar inc": "Shefali",
  "drift dynamics llc": "Assem & Saood",
  "dunn's valve testers inc": "Micah Simmons",
  "eisa enterprises llc": "Humaira",
  "emesa 9115 llc": "Sarah Alabaykan",
  "emesa hills llc": "Sarah Alabaykan",
  "emesa investments llc": "Sarah Alabaykan",
  "engage iq labs llc": "Benny Singh",
  "eta real estate llc": "Joseph McCamish Group",
  "faptl series llc": "Jamil Hasan",
  "farida and ali ebrahim trust": "Ebrahim Mo & Ali",
  "fast & best auto llc": "Altousa",
  "fazeli investment group llc": "Altousa",
  "flex space connect llc": "Hamza",
  "for a place to live llc": "Jamil Hasan",
  "fred & soody sharifi family partnership ltd": "SFT",
  "fred & soody sharifi gp llc": "SFT",
  "frisco 3056 preston llc": "Saritha",
  "fusion iq labs llc": "Benny Singh",
  "galloper chauffeured services llc": "Ghaz Hamdani",
  "gambhir & hasan llc": "Jamil Hasan",
  "gambhir property at 614 marshall llc": "Baljit/B S Gambhir Family Ptr",
  "gambhirs graustark property llc": "Baljit/B S Gambhir Family Ptr",
  "gastro concepts lp": "Shammi",
  "gem technology inc": "Vikas Sodhani",
  "genisis capital inc (de)": "Jiten",
  "global dealership services llc": "Moe Elmorabit",
  "global infra engicon llc": "Manish Maheshwari",
  "global omni llc": "Manish Maheshwari",
  "grand prix auto ventures llc": "Kafil M",
  "green hill hospitality inc": "Farida Mangalji",
  "hamza invests fund a llc": "Hamza",
  "hamza invests fund f llc": "Hamza",
  "hamza invests fund k llc": "Hamza",
  "hamza invests fund r llc": "Hamza",
  "hamza invests fund ry llc": "Hamza",
  "hamza invests fund u llc": "Hamza",
  "hamza invests fund z llc": "Hamza",
  "hamza invests legacy land llc": "Hamza",
  "hamza invests llc": "Hamza",
  "houston bus services inc": "Ron",
  "houston direct llc": "Amanul Syed",
  "houston limos llc": "Ron Group",
  "houston squash & fitness club llc": "Sadiq Mohd",
  "ila design group llc": "Vikas Sodhani",
  "imran dar md pllc": "Dr Bushra",
  "inca roca group corp": "Parodi",
  "inv software solutions llc": "Jay Pasala",
  "ispada llc": "Eduardo",
  "jain management llc": "RPBS/Vibhore Jain",
  "jann ventures ii company llc": "Amin Lakhani",
  "jann ventures llc": "Amin Lakhani",
  "jhaveri group llc": "Shefali",
  "jhaveri investments llc": "Shefali",
  "jhaveri properties llc": "Shefali",
  "jhaveri squared llc": "Shefali",
  "joshua ventures llc": "Shah",
  "jrrv gp llc": "Jiten",
  "jrrv lp": "Jiten",
  "kalcorp enterprises inc": "Kalcorp",
  "kalgroup partners llc": "Kalcorp",
  "kalgroup properties lp": "Kalcorp",
  "karm business llc (coco fulshear)": "Amrish",
  "kb kitchen & bath remodeling llc": "Sam Samara Group",
  "lakh enterprises llc": "Amin Lakhani",
  "leader engineering inc": "Vipandeep",
  "linh enterprises llc": "Dr Almas",
  "live oak pat booker llc": "Saritha",
  "lonestar derivatives inc": "Manish Maheshwari",
  "maa clover lane inc": "Humaira Group",
  "maggie property management llc": "Shah",
  "makani foundation": "Dr Bushra",
  "malik 786 investments llc": "Malik",
  "malik gas & grocery llc": "Malik",
  "malik petroleum corporation": "Malik",
  "marace realty co llc": "Josh Davis",
  "margalla hills holding": "Assem Ahmed",
  "max box rentals llc": "Josh Davis",
  "maxificient inc": "Amrish",
  "mayfair assets llc": "Farida Mangalji",
  "mcduffie & branard llc": "Baljit Gambhir",
  "mdcare global llc": "Dr Subhash Bannerji",
  "medical uniform manufacturing inc": "Ebrahim Mo & Ali",
  "mexba llc": "Amanul Syed",
  "mg2 enterprise llc": "Malik",
  "michigan nine llc": "John Page",
  "mid-tex services llc": "Cathi Davis",
  "miller wiley franchises corp": "Jimmy Miller",
  "miller wiley ventures llc (dba/linx energy partners)": "Jimmy Miller",
  "miran holdings llc": "Assem Ahmed",
  "mixit it fresh llc": "Kalcorp",
  "mohammed j. ebrahim family trust": "Ebrahim Mo & Ali",
  "moi wellness and aesthetics pllc": "Dr Andrew Khoury Group",
  "mumu mandarin llc": "Reza Chawla",
  "nbc sub llc": "Siju Tom",
  "neches river printing llc": "Vipandeep Group",
  "nederland magic llc": "Vipandeep Group",
  "nexus anesthesia associates llc": "Dr Almas",
  "nexus heritage america inc": "Kafil M",
  "nimitz properties llc": "Kalcorp",
  "nketechnica llc": "Humaira",
  "north texas rheumatology pa": "Dr Subhash Bannerji",
  "novare homes llc": "Jacopo Pizzi",
  "nst group llc": "Siju Tom",
  "opal real estates llc": "Raj K",
  "pampered poh llc": "Harpal Dhaliwal",
  "parisara enterprises llc": "Shefali",
  "parodi group inc": "Parodi",
  "parodi holdings llc": "Pardoi Group",
  "perpetual printing inc": "Kalcorp",
  "prabhguru llc": "Paul Sikand",
  "pricewise towing llc": "Malik",
  "pristine energy llc (dba san marcos apartment)": "Shonali",
  "priya management inc": "Pintu",
  "priyaprachi investments llc": "Pintu",
  "quantai llc": "Jiten",
  "qureshi enterprises llc": "Humaira",
  "rahul agarwal heritage trust": "Jiten",
  "rama trading inc": "RPBS/Outside Shareholders",
  "rapd's investments llc": "Puneet Dhamija",
  "rapid progress digital llc": "Rajesh Dharamshi",
  "re southbelt llc": "Eduardo",
  "red oak 35 llc": "Saritha",
  "replico enterprises inc": "RPBS/Outside Shareholders",
  "research periodicals & book serv inc": "RPBS/Anand & Bela",
  "rh&zz company llc": "Sadiq Mohd",
  "right medical billing llc": "Humaira",
  "rising sail westlake llc": "VKC",
  "rocky mountain inc (co)": "RPBS/Outside Shareholders",
  "roshlo llc (fl)": "Nirav Patel",
  "rotana group llc": "John Page",
  "round rock henna llc": "Saritha",
  "royal academic inc (mi)": "RPBS/Outside Shareholders",
  "royal logistics & warehousing inc": "RPBS/Outside Shareholders",
  "rpbs llc": "RPBS/Anand & Bela",
  "rsf gym llc": "VKC",
  "rss inc": "Benny Singh",
  "s r trading inc": "RPBS/Outside Shareholders",
  "sabbahi & makani pllc": "Dr Rabob",
  "sabe enterprises llc": "Humaira",
  "sai nalanda inc (aka arka montessori academy)": "Jaya Sripada",
  "saleswilling inc": "Harpal Dhaliwal",
  "san savs management lp": "Shonali",
  "sarah simmons md pllc": "Micah Simmons",
  "sas nutrition llc (dba nutrition depot)": "Ali Nasser",
  "sauson bus inc (pka houston bus, inc.)": "Ron",
  "sauson investment group llc": "Ron",
  "savs lp": "Shonali",
  "scada-ing inc": "Sadiq Mohd",
  "sg vibhava llc": "Jaya Sripada",
  "shah haleem brokerage llc": "Shah",
  "sharp international inc (mi)": "RPBS/Outside Shareholders",
  "shepherd rv park llc": "Harpal Dhaliwal",
  "shiv108 llc (fl)": "Nirav Patel",
  "shiv109 llc (fl)": "Nirav Patel",
  "shooting dynamics of tx llc": "Assem Ahmed",
  "sienna morris properties llc": "Peter M",
  "sll transportation llc": "Ron",
  "smzj holdings llc": "Shah",
  "snh real estate llc": "Baljit Gambhir",
  "soap scada engineering llc": "Sadiq Mohd",
  "solitara llc": "Shefali",
  "sontrin apartments llc": "Shonali",
  "spill containment solutions inc": "Josh Davis",
  "spur-cross ranch llc": "Steve Foster",
  "sq organization inc": "RPBS/Outside Shareholders",
  "ss marketing inc": "RPBS/Outside Shareholders",
  "sskd family partnership lp": "Saritha",
  "sskd gp llc": "Saritha",
  "stillwood properties llc": "Jamil Hasan",
  "stoic services llc": "Cathi Davis",
  "stonecliff holdings lp": "Khemka",
  "stripes burrito llc": "VKC",
  "stripes burrito mgmt llc": "VKC",
  "stripes real estate llc": "VKC",
  "submoa llc": "Assem Ahmed",
  "sunstone development inc": "Steve Foster",
  "sunstone land co llc": "Steve Foster",
  "suvira group llc": "Shonali",
  "system logistics distribution llc": "Peter M",
  "tarr 3420 rosedale llc": "Jamil Hasan",
  "tekexpro llc": "Srilatha Valluri",
  "the cedar tree mediterranean grill & caf\u00e9 llc": "Kafil M",
  "the devan kotagiri irrv tr": "Saritha",
  "the kaveri kotagiri irrv trust": "Saritha",
  "the langford at seven mile llc (mi)": "John Page",
  "the langford at telegraph llc (mi)": "John Page",
  "the langford group llc (mi)": "John Page",
  "top spin realty llc": "Dr Bushra",
  "touch-tel usa llc": "Amanul Syed",
  "trobel consulting llc": "RPBS/Avi Jain",
  "trutek llc": "Harpal Dhaliwal",
  "tx99 holdings llc": "Shah",
  "ugra holding llc": "Benny Singh",
  "unbridaled diamonds inc": "Vikas Sodhani",
  "union trust": "Ron",
  "usa investment group llc": "Sam Samara",
  "v & a partnership ltd": "RPBS/Vibhore Jain",
  "valvitalia usa inc": "Leslie Bernal",
  "varun agarwal heritage trust": "Jiten",
  "veridian group llc": "John Page",
  "veritas prepaid phone company llc": "Amanul Syed",
  "vertex organization llc": "RPBS",
  "vkc delights group llc": "VKC",
  "vkc group inc": "VKC",
  "vkc i gp llc": "VKC",
  "vkc i lp": "VKC",
  "vkc properties gp llc": "VKC",
  "vkc properties lp": "VKC",
  "vkc realty llc": "VKC",
  "vyrion technologies llc": "Humaira Group",
  "wealth integration system for entrepreneurs inc": "Ali Nasser",
  "westmore community llc": "Jamil Hasan",
  "westmore on ennis llc": "Jamil Hasan",
  "zarek rental llc": "Shah",
  "zulfik enterprises inc": "Farida Mangalji",
};


export async function GET() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!url || !key) {
    return NextResponse.json({ error: "Missing env vars" }, { status: 500 });
  }

  const supabase = createClient(url, key, { db: { schema: "tap_hub_project" } });
  const results: Record<string, unknown> = {};

  // Fix 1: Strip leading " from names
  const { data: quoted, error: qErr } = await supabase
    .from("clients")
    .select("id, name")
    .like("name", '"%');

  if (qErr) {
    results.quote_error = qErr.message;
  } else {
    results.quotes_found = quoted?.length || 0;
    let fixed = 0;
    if (quoted) {
      for (const c of quoted) {
        const clean = c.name.replace(/^"+/, "");
        if (clean !== c.name) {
          const { error } = await supabase
            .from("clients")
            .update({ name: clean })
            .eq("id", c.id);
          if (!error) fixed++;
        }
      }
    }
    results.quotes_fixed = fixed;
  }

  // Fix 2: Update groups from sheet data
  let groupsUpdated = 0;
  const { data: allClients, error: cErr } = await supabase
    .from("clients")
    .select("id, name, group_owner")
    .limit(2000);

  if (cErr) {
    results.group_error = cErr.message;
  } else {
    results.clients_checked = allClients?.length || 0;
    if (allClients) {
      for (const c of allClients) {
        const key = c.name.trim().toLowerCase();
        const newGroup = GROUP_MAP[key];
        if (newGroup && c.group_owner !== newGroup) {
          const { error } = await supabase
            .from("clients")
            .update({ group_owner: newGroup })
            .eq("id", c.id);
          if (!error) groupsUpdated++;
        }
      }
    }
    results.groups_updated = groupsUpdated;
  }

  return NextResponse.json(results);
}
